### ISSUE TITLE
git新人表示感谢。

### ISSUE THREAD

**Issue by programmerC** [saitjr/ReactiveCocoa-MVVM-AFNetworking-FMDB#1]
初学ReactiveCocoa，看了Up主的code更加清晰了解了MVVM架构模式，ViewModel主要是想剖出ViewController的业务逻辑和页面逻辑，但是我想问的是如果在Up主的项目里面有对UITableView的稍微复杂一点使用的话，怎么把处理过程处理于ViewModel层，比如说cell的点击push操作，cell上面的点击回调等等，希望Up主得空的时候可以稍微做做，让新人了解一下，感谢。

**Comment by saitjr** [comment]
我的处理方式一般有两种：
1. 简单的push操作，可以直接在cell中获得它所属的viewController，然后用viewController来push；
2. 如果会有比较复杂的操作，比如涉及到数据删除等，我选择用block或者delegate，把操作传到viewcontroller中处理。

**Comment by programmerC** [comment]
感谢回复，受宠若惊！
1.通过cell获取它所属的viewController这个，这个我不太明白，请大大教教；点击cell上面的按钮，我一般是通过block回调实现，如果是直接点击cell的话，
就是直接在delegate的一个方法里面操作。
2.我的语言大概会比较乱哦，请谅解。通过block回调或者delegate去处理，把操作又放到了viewController里面，这似乎有些违背的viewModel设计，又把
（大量or少量）逻辑处理代码或其他放到了viewController里面，我想问的是 是不是有些时候这些操作是不可避免的？或许是我刚学ReactiveCocoa的关系，什么东西都想往这边靠，什么东西都想放到viewModel里面处理，一昧追求viewController的简洁。
3.该用Block的时候用Block，该用delegate的时候用delegate，该使用viewModerl的时候使用viewModel，刚开始学ReactiveCocoa什么都用想里面的方法来实现，我大概还无法区分它们的正确使用时机。希望大大帮忙点通一下。
最后，感谢您百忙之中回复我，回复内容发到我的邮箱了，似乎是国外的时间，希望回复不会打扰到您，再次感谢！

**Comment by saitjr** [comment]
不会打扰，貌似是获取的国外时间...
1. cell中获取viewController的意思就是一层一层往上找，找到viewController。代码在这：https://github.com/saitjr/TKit/blob/master/TKit/TUIs/Category/UIView%2BTBasicTools.m
这个文件中的currentViewController方法。
1. 我理解的viewModel并不是处理逻辑，而是处理数据。所以cell的事件到viewController中处理还好。如果不用delegate或者block，也完全可以用rac的command来检测按钮点击事件。
2. 关于什么时候该用什么，这要看具体情景了。cell的事件用block和delegate都可以，唯一需要注意的就是block的内存问题。
