### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SteamPunkMao** [saitjr/ReactiveCocoa-MVVM-AFNetworking-FMDB#2]
三方库MJExtension文件缺失，需要重新pod， _categoyrText = [@"分类:" stringByAppendingString:self.articleModel.categoryname];self.articleModel.categoryname为nil，导致崩溃。

**Comment by saitjr** [comment]
好的，谢谢，修复中

**Comment by shijianmei** [comment]
报错，大兄弟， no such file or directory: '/Users/jianmei/Downloads/ReactiveCocoa-MVVM-AFNetworking-FMDB-master/Pods/MJExtension/MJExtension/MJDictionaryCache.m'
clang: error: no input files

**Comment by saitjr** [comment]
已修改。
顺便将以前有问题的地方也修改了。
