### ISSUE TITLE
运行后, 没有任何数据

### ISSUE THREAD

**Issue by GCIOS** [saitjr/ReactiveCocoa-MVVM-AFNetworking-FMDB#3]
@"https://s0.jianshuapi.com/v2/trending/daily.json?app%5Bname%5D=hugo&app%5Bversion%5D=2.11.2&auth1=8505f184ed6b87f1ffa152474174c17c&count=10&device%5Bguid%5D=63926467-1049-49DF-8CDA-15D8E596E742&limit=10&page=1&timestamp=1478249390"

**Comment by saitjr** [comment]
之前随手找的接口，正在更新为稳定接口

**Comment by saitjr** [comment]
久等，已修复
