### ISSUE TITLE
再轻量化 ViewModel

### ISSUE THREAD

**Issue by tangzzz-fan** [saitjr/ReactiveCocoa-MVVM-AFNetworking-FMDB#5]
之前看了 MVVM 的部分东西, 理解是, ViewModel 应该只负责处理 UI 相关的状态. 绑定等等, 现在项目中的 ViewModel 中包含了网络请求, 本地数据访问操作. 这些都与 UI 操作无关, 是不是可以由 Model 层暴露出一些处理协议做这些与 UI 无关的事?
另外. 想问一下, 这里面的组件化可以怎么做? 比如几个模块之间的页面交互, 数据交互, 这个有好一点的实践吗?

**Comment by saitjr** [comment]
请求与数据持久化，可以抽象成 S 层，可以看看京东金融 MVCS 框架的事件，里面的模块之间通信，采用的是 KVC。不过在这点上，我不觉得不太好，KVC 满天飞维护起来成本也挺高。

**Comment by tangzzz-fan** [comment]
谢谢~
